force download from Dreamhost

diff --git a/.github/workflows/mirror.yml b/.github/workflows/mirror.yml
--- a/.github/workflows/mirror.yml
+++ b/.github/workflows/mirror.yml
@@ -36,11 +36,12 @@ jobs:
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
-
+      - name: Change hosts file
+        run: echo "173.236.255.166 www.dcpbk.org" | sudo tee -a /etc/hosts
       - name: Download the files
-        run: wget -m --retry-connrefused --tries=20 --no-host-directories --directory-prefix="www" --exclude-directories="/wp-json,/wp-admin" --regex-type 'pcre' --reject-regex '.*\?(?!ver).*|xmlrpc\.php$' --wait 1 https://www.dcpbk.org/
+        run: wget --no-check-certificate -m --retry-connrefused --tries=20 --no-host-directories --directory-prefix="www" --exclude-directories="/wp-json,/wp-admin" --regex-type 'pcre' --reject-regex '.*\?(?!ver).*|xmlrpc\.php$' --wait 1 https://www.dcpbk.org/
       - name: Download 404
-        run: wget --content-on-error --directory-prefix="www" https://www.dcpbk.org/404.html || echo "Expexted error"
+        run: wget --no-check-certificate --content-on-error --directory-prefix="www" https://www.dcpbk.org/404.html || echo "Expexted error"
 
       - name: Setup Pages
         uses: actions/configure-pages@v3
