adapt for static

diff --git a/.github/workflows/mirror.yml b/.github/workflows/mirror.yml
--- a/.github/workflows/mirror.yml
+++ b/.github/workflows/mirror.yml
@@ -37,33 +37,10 @@ jobs:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
 
-      #- name: Restore the file attrs (mtime)
-      #  run: |
-      #    if [ -d "www" ]
-      #    then
-      #      .github/bin/save-file-attrs.py restore
-      #    else
-      #      mkdir www
-      #    fi
-
       - name: Download the files
-        run: wget -m --retry-connrefused --tries=20 --no-host-directories --directory-prefix="www" --exclude-directories="/wp-json,/wp-admin" --regex-type 'pcre' --reject-regex '.*\?(?!ver).*' --wait 1 https://chriskthomas.com/
+        run: wget -m --retry-connrefused --tries=20 --no-host-directories --directory-prefix="www" --exclude-directories="/wp-json,/wp-admin" --regex-type 'pcre' --reject-regex '.*\?(?!ver).*' --wait 1 https://www.dcpbk.org/
       - name: Download 404
-        run: wget --content-on-error --directory-prefix="www" https://chriskthomas.com/404.html || echo "Expexted error"
-
-      #- name: Save the file attrs
-      #  run: .github/bin/save-file-attrs.py save
-
-      #- name: Commit files
-      #  run: |
-      #    git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
-      #    git config --local user.name "github-actions[bot]"
-      #    git add -- ./www
-      #    git diff-index --cached --quiet HEAD -- || git add .saved-file-attrs
-      #    git commit -m "automatically update site" || echo "Error (probably no changes to commit)"
-
-      #- name: Push changes
-      #  run: git push
+        run: wget --content-on-error --directory-prefix="www" https://www.dcpbk.org/404.html || echo "Expexted error"
 
       - name: Setup Pages
         uses: actions/configure-pages@v3
@@ -74,7 +51,7 @@ jobs:
       - name: Remove query strings from file names
         run: .github/bin/cleanup-querystrings.py
       - name: Replace text
-        run: find ./dist/ -type f -exec sed -i "s/https:\/\/chriskthomas.com\/\?/\//g" {} \;
+        run: find ./dist/ -type f -exec sed -i -E "s|https?://www\.dcpbk\.org(/?)|https://mwt.github.io/static-dcpbk\1|g" {} \;
       - name: Copy robots.txt
         run: cp robots.txt dist/ 
 
